"""add exchange to watchlist

Revision ID: 849d13b41ad1
Revises: 509ab361cd52
Create Date: 2026-10-08 17:05:09.647444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849d13b41ad1'
down_revision: Union[str, Sequence[str], None] = '509ab361cd52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlists', sa.Column('exchange', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watchlists', 'exchange')
    # ### end Alembic commands ###
